# Generated by Django 3.2.4 on 2021-06-22 19:55

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_photos', cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='images')),
                ('caption', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CreativeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudioUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StudioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=30)),
                ('rates', models.DecimalField(decimal_places=2, max_digits=8)),
                ('logo', cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='images')),
                ('advert_photos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studioapp.advertpost')),
                ('service_provided', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studioapp.services')),
                ('studio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studioapp.studiouser')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('creative_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studioapp.creativeuser')),
            ],
        ),
        migrations.CreateModel(
            name='CreativeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='images')),
                ('bio', models.CharField(max_length=100)),
                ('creative_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studioapp.creativeuser')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('session_duration', models.DurationField()),
                ('session_time', models.DateTimeField()),
                ('creative_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studioapp.creativeuser')),
                ('studio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studioapp.studioprofile')),
            ],
        ),
        migrations.AddField(
            model_name='advertpost',
            name='studio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studioapp.studiouser'),
        ),
    ]
